version: "3.8"

services:

  postgres:
    image: postgres
    container_name: faceit-postgres
    environment:
      POSTGRES_DB: faceitDb
      POSTGRES_USER: faceitUser
      POSTGRES_PASSWORD: faceitPass

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U faceituser"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - faceit_network


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: faceit-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"

    networks:
      - faceit_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: faceit-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - faceit-network

  db-saver:
    build:
      context: ./db_saver
      dockerfile: Dockerfile
    container_name: faceit-db-saver
